### ISSUE TITLE
Disable Save button for index and subindex forms

### ISSUE THREAD

**Issue by tsdima** [amida-tech/greyscale#38]
At forms for adding and editing indexes and subindexes (for projects) does not disabled "Save" button if user have not filled all required fields. 
Therefore, when save, API return errors like:
{ '!': 0,     e: 403,     message: 'title, divisor, weights fields are required' }

branch: launch_demo

**Comment by hrickards** [comment]
@kachok Fixed in index-aggregation-tweaks (comparative viz branch) and cherrypicked into index-fixes branch ready for merge into launch-demo

**Comment by hrickards** [comment]
Merged
